export const ADD_ORDER_ITEMS_IN_ORDER_DETAIL_REQUEST =
  "ADD_ORDER_ITEMS_IN_ORDER_DETAIL_REQUEST";

export const ADD_ORDER_ITEMS_IN_ORDER_DETAIL_SUCCESS =
  "ADD_ORDER_ITEMS_IN_ORDER_DETAIL_SUCCESS";

export const ADD_ORDER_ITEMS_IN_ORDER_DETAIL_FAIL =
  "ADD_ORDER_ITEMS_IN_ORDER_DETAIL_FAIL";

export const ADD_ADDRESS_IN_ORDER_DETAIL_REQUEST =
  "ADD_ADDRESS_IN_ORDER_DETAIL_REQUEST";

export const ADD_ADDRESS_IN_ORDER_DETAIL_SUCCESS =
  "ADD_ADDRESS_IN_ORDER_DETAIL_SUCCESS";

export const ADD_ADDRESS_IN_ORDER_DETAIL_FAIL =
  "ADD_ADDRESS_IN_ORDER_DETAIL_FAIL";

export const PAYMENT_CHARGE_REQUEST = "PAYMENT_CHARGE_REQUEST";

export const PAYMENT_CHARGE_SUCCESS = "PAYMENT_CHARGE_SUCCESS";

export const CARTLIST_EMPTY = "CARTLIST_EMPTY";

export const ORDER_DETAILS_EMPTY = "ORDER_DETAILS_EMPTY";

export const PAYMENT_CHARGE_FAIL = "PAYMENT_CHARGE_FAIL";

export const CLEAR_ORDER_REQUEST = "CLEAR_ORDER_REQUEST";

export const CLEAR_ORDER_SUCCESS = "CLEAR_ORDER_SUCCESS";

export const CLEAR_ORDER_FAIL = "CLEAR_ORDER_FAIL";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";

export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";

export const CLEAR_CART_FAIL = "CLEAR_CART_FAIL";

export const CLEAR_USER_CARTITEM_SUCCESS = "CLEAR_USER_CARTITEM_SUCCESS";

export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_FAIL = "GET_ORDER_LIST_FAIL";
